### ISSUE TITLE
_test_transaction(): breaks at line "var txid = yield(algod.send_transaction(stx), "completed")"

### ISSUE THREAD

**Issue by Sam2much96** [lucasvanmol/algodot#2]
Godot IDE throws out these errors:

Main Error : First argument of yield() not of type object.

E 0:00:06.390   <unset>: Request(RequestError { url: Some("http://localhost:8980/v2/transactions/params"), details: Http { status: 400, message: "invalid input: unable to parse base32 digest data 'txid': illegal base32 data at input byte 0" } })
  <C++ Source>  algodot/src/algod/mod.rs:392 @ <unset>()

E 0:00:06.390   Algodot :: construct_payment: cannot convert argument `params` (#0, Nil(Null)) to "SuggestedTransactionParams": invalid variant type: expected Dictionary, got Nil (non-primitive types may impose structural checks)
  <C++ Source>  algodot/src/algod/mod.rs:183 @ Algodot :: construct_payment()
  <Stack Trace> main.gd:108 @ _test_transaction()

E 0:00:06.390   Algodot :: sign_transaction: cannot convert argument `txn` (#0, Nil(Null)) to "Transaction": invalid variant type: expected Dictionary, got Nil (non-primitive types may impose structural checks)
  <C++ Source>  algodot/src/algod/mod.rs:172 @ Algodot :: sign_transaction()
  <Stack Trace> main.gd:109 @ _test_transaction()

E 0:00:06.390   Algodot :: sign_transaction: cannot convert argument `txn` (#0, Nil(Null)) to "Transaction": invalid variant type: expected Dictionary, got Nil (non-primitive types may impose structural checks)
  <C++ Source>  algodot/src/algod/mod.rs:172 @ Algodot :: sign_transaction()
  <Stack Trace> main.gd:109 @ _test_transaction()

E 0:00:06.639   <unset>: gdnative-core: method panicked (check stderr for output)
  <C++ Source>  <unset>:0 @ <unset>()
  <Stack Trace> main.gd:110 @ _test_transaction()

E 0:00:06.850   <unset>: property url on native class Algodot does not have a getter
  <C++ Source>  /cargo/registry/src/github.com-1ecc6299db9ec823/gdnative-core-0.10.0/src/export/property/invalid_accessor.rs:68 @ <unset>()
  <Stack Trace> main.gd:110 @ _test_transaction()

E 0:00:06.850   <unset>: property token on native class Algodot does not have a getter
  <C++ Source>  /cargo/registry/src/github.com-1ecc6299db9ec823/gdnative-core-0.10.0/src/export/property/invalid_accessor.rs:68 @ <unset>()
  <Stack Trace> main.gd:110 @ _test_transaction()

E 0:00:06.850   <unset>: property headers on native class Algodot does not have a getter
  <C++ Source>  /cargo/registry/src/github.com-1ecc6299db9ec823/gdnative-core-0.10.0/src/export/property/invalid_accessor.rs:68 @ <unset>()
  <Stack Trace> main.gd:110 @ _test_transaction()

E 0:02:29.716   <unset>: property url on native class Algodot does not have a getter
  <C++ Source>  /cargo/registry/src/github.com-1ecc6299db9ec823/gdnative-core-0.10.0/src/export/property/invalid_accessor.rs:68 @ <unset>()
  <Stack Trace> main.gd:110 @ _test_transaction()

E 0:02:29.716   <unset>: property token on native class Algodot does not have a getter
  <C++ Source>  /cargo/registry/src/github.com-1ecc6299db9ec823/gdnative-core-0.10.0/src/export/property/invalid_accessor.rs:68 @ <unset>()
  <Stack Trace> main.gd:110 @ _test_transaction()

E 0:02:29.716   <unset>: property headers on native class Algodot does not have a getter
  <C++ Source>  /cargo/registry/src/github.com-1ecc6299db9ec823/gdnative-core-0.10.0/src/export/property/invalid_accessor.rs:68 @ <unset>()
  <Stack Trace> main.gd:110 @ _test_transaction()

**Comment by Sam2much96** [comment]
I've setup my sandbox environment and generated an address and mnemonic which i set in the Algod initialization function, test node is also running in a shell environment. 

Thank you Dev!

**Comment by Sam2much96** [comment]
it starts breaking from var tx = algod.construct_payment( params, funder_address, account[0], 123456789)

My best guess? either the parameters are wrong, or their methods are depreciated. I may be wrong, but I'm just guessing here.

**Comment by Sam2much96** [comment]
Solution: I used the url from my sandbox environment "http://localhost:8980". The library doesn't like that apparently. So future users,
Dont change "algod.url = http://localhost:4001" to whatever your algod sandbox uses, it'll throw out this error above!

closing issue now!

**Comment by lucasvanmol** [comment]
If you're running the sandbox environment, by default the algod port is `4001`. `8980` is the default for the indexer port, which isn't what Algodot expects.

**Comment by Sam2much96** [comment]
Ohhh, Alright, Noted. I'll be writing a little Documentation on all of this once I'm done debugging.
